[package]
name = "wolf_engine"
description = "A game framework with a focus on flexibility and ease of use."
version = "0.24.0"
authors = ["AlexiWolf <alexiwolf@pm.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlexiWolf/wolf_engine"
homepage = "https://github.com/AlexiWolf/wolf_engine"

[dependencies]
wolf_engine_core = {path = "wolf_engine_core"}
wolf_engine_framework = {path = "wolf_engine_framework", optional = true}

[dev-dependencies]
log = "0.4"

[features]
default = ["framework"]
framework = ["wolf_engine_framework"]
logging = ["framework", "wolf_engine_core/logging"]

[workspace]
members = ["wolf_engine_*"]
