[package]
name = "wolf_engine"
version = "0.1.0"
authors = ["AlexiWolf <alexiwolf@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
lazy_static = "1.4"
colored = "2"
chrono = "0.4"


[dev-dependencies]
test-case = "1.2"
simple_logger = "1.13"