[package]
name = "wolf_engine"
description = "A game framework with a focus on flexibility and ease of use."
version = "0.26.0"
authors = ["AlexiWolf <alexiwolf@pm.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlexiWolf/wolf_engine"
homepage = "https://github.com/AlexiWolf/wolf_engine"
keywords = ["wolf-engine", "game", "gamedev"]
categories = ["game-development", "game-engines"]

[dependencies]
resources = "1.1.0"
wolf_engine_core = {path = "wolf_engine_core", version = "0.26.0"}
wolf_engine_framework = {path = "wolf_engine_framework", version = "0.26.0", optional = true}
wolf_engine_window = {path = "wolf_engine_window", version = "0.26.0", optional = true}

[dev-dependencies]
log = "0.4"

[features]
default = ["framework", "parallel"]
framework = ["wolf_engine_framework"]
logging = ["framework", "wolf_engine_core/logging"]
window = ["wolf_engine_window"]
serde = ["wolf_engine_core/serde", "wolf_engine_window/serde"]
parallel = ["wolf_engine_core/parallel"]
extended_tuple_impls = ["wolf_engine_core/extended_tuple_impls"]

[workspace]
members = ["wolf_engine_*"]

[[example]]
name = "logging"
required-features = ["logging"]

[[example]]
name = "plugins"
required-features = ["framework"]
