[package]
name = "wolf_engine"
description = "A game framework with a focus on flexibility and ease of use."
version = "0.13.0"
authors = ["AlexiWolf <alexiwolf@pm.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlexiWolf/wolf_engine"
homepage = "https://github.com/AlexiWolf/wolf_engine"

[dependencies]
log = "0.4"
anymap = "0.12"
rc_event_queue = "0.4"

# Optional Dependencies

simple_logger = {version = "1.13", optional = true}

[dev-dependencies]
lazy_static= "1.4"
test-case = "1.2"
mockall = "0.11"

[features]
logging = ["simple_logger"]

