[package]
name = "wolf_engine"
description = "A game framework with a focus on flexibility and ease of use."
version = "0.1.0"
authors = ["AlexiWolf <alexiwolf@pm.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AlexiWolf/wolf_engine"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
lazy_static = "1.4"
colored = "2"
chrono = "0.4"
simple_logger = "1.13"

[dev-dependencies]
test-case = "1.2"
mockall = "0.11"


