[package]
name = "wolf_engine_codegen"
version = "0.26.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
proc-macro2 = "1.0"
thiserror = "1.0"
