name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    name: Tests

    strategy:
      fail-fast: false
      matrix:
        rust-version: 
          - stable 
          - nightly
        platform:
          - { os: ubuntu-latest }
          - { os: windows-latest }
          - { os: macos-latest }

    env:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
      FEATURES: ${{ format(',{0}', matrix.platform.features ) }}
      OPTIONS: ${{ matrix.platform.options }}

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust-version }} 

    - name: Run tests
      shell: bash
      run: cargo test --verbose $OPTIONS --features $FEATURES

